all:
  hosts:
    node1:
      ansible_host: 192.168.30.10
      ip: 192.168.30.10
      access_ip: 192.168.30.10

  children:
    kube-master:
      hosts:
        node1:

    kube-node:
      hosts:
        node1:

    etcd:
      hosts:
        node1:

    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
